name: Pokedex

on:
  push:
    branches:
      - master
jobs:
  simple_deployment_pipeline:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'
      
      - name: install Dependencis
        run: npm install
      
      - name: Code Linting (with Fix)
        run: npm run eslint -- --fix

      - name: Build
        run: npm run build
      
      - name: Run Tests
        run: npm test

